version: '3.8'

services:
  api:
    container_name: "${PROJECT_COMPANY}-${API_NAME}-api"
    build:
      context: ./
      target: development
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      NODE_ENV: development
